theme = "dimension"
languagecode = "no"
title = 'Praksis hos <object data="vidi-logo.svg" style="height: 1em" alt="Vidi"></object>'

[params]
  description = 'A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br/>
                for free under the <a href="https://html5up.net/license">Creative Commons</a> license.'
  logo = "/favicon.ico"
copyright = "Martin Kleiven"