theme = "dimension"
languagecode = "no"
title = 'Praksis hos <object data="vidi-logo.svg" style="height: 1em" alt="Vidi"></object>'

[params]
  description = 'En presentasjon av praksis hos <a href="https://vidi.no/">Vidi</a>'
  logo = "/favicon.ico"
copyright = "Martin Kleiven"